name: Parallel Cypress Tests

on:
  push:
    branches: master
  schedule:
    - cron: '0 12 * * 2'

jobs:
  cross-browser:
    runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node12.16.1-chrome80-ff73
#       options: --user 1001
    strategy:
      matrix:
      # the actual items in the array do not matter,
      # just the number - to force CI to sping 3 copies
      # of the current job in parallel
        machines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1
        
        
      - name: Electron
        uses: cypress-io/github-action@v2
        with:
          browser: electron
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 300
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: Chrome Browser Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
#           start: yarn start
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 300
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
